In [1]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
pd.DataFrame([], columns=["Macro-F1", "Balanced Accuracy", "Macro Recall", "Macro Precision"])

Empty DataFrame
Columns: [Macro-F1, Balanced Accuracy, Macro Recall, Macro Precision]
Index: []

In [2]:
df = pd.DataFrame({
    "text": [
        "machine learning",
        "deep learning",
        "machine intelligence",
        "learning systems"
    ]
})

In [3]:
count_vec = CountVectorizer()

count_matrix = count_vec.fit_transform(df["text"])
count_df = pd.DataFrame(
    count_matrix.toarray(),
    columns=[f"bow_{w}" for w in count_vec.get_feature_names_out()]
)

In [4]:
count_df

   bow_deep  bow_intelligence  bow_learning  bow_machine  bow_systems
0         0                 0             1            1            0
1         1                 0             1            0            0
2         0                 1             0            1            0
3         0                 0             1            0            1